FROM --platform=$TARGETOS/$TARGETARCH debian:bullseye-slim

LABEL author="Alternight drysius" maintainer="danielolxlol@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN useradd -m -d /home/container -s /bin/bash container -u 998 container

RUN ln -s /home/container/ /nonexistent

ENV USER=container HOME=/home/container

## Update base packages
RUN apt update \
             && apt upgrade -y

RUN apt-get install -y make gcc pkg-config libvpx-dev libx264-dev libopus-dev libsdl2-dev

WORKDIR     /home/container

COPY        ./entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]
