FROM node:20-alpine AS node
FROM alpine:3.20

LABEL author="Ashu" maintainer="Matheusn.biolowons@gmail.com"

ENV LD_PRELOAD="/usr/lib/preloadable_libiconv.so"

RUN apk add --no-cache --virtual=build-dependencies --upgrade \
    ca-certificates \
    wget \
    jq \
    tar \
    curl \
    nginx \
    unzip \
    git

    RUN echo "**** Instalação dos php ****" && \
    apk add --no-cache --update \
    php \
    php-bcmath \
    php-cli \
    php-common \
    php-dom \
    php-curl \
    php-intl \
    php-fileinfo \
    php-fpm \
    php-gd \
    php-mbstring \
    php-mysqli \
    php-pdo \
    php-pdo_mysql \
    php-phar \
    php-posix \
    php-session \
    php-simplexml \
    php-sodium \
    php-tokenizer \
    php-xml \
    php-zip \ 
    php-sockets \
    php-ctype

RUN apk add --no-cache redis
COPY --from=composer:latest  /usr/bin/composer /usr/bin/composer

# Esse codigo o drysius me passou
# Instala o bash a
RUN apk add --no-cache bash fakeroot
# Remove o link simbólico para o shell padrão e cria um novo link simbólico para o bash
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

RUN set -eux \
    & apk add \
        --no-cache \
        yarn

RUN echo "UTC" > /etc/timezone

COPY ./crontab_test.sh /
RUN chmod 777 /crontab_test.sh

USER container
ENV  USER container
ENV HOME /home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD [ "bash", "/entrypoint.sh" ]
